[2022-02-19 21:36:08,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data manual__2022-02-19T21:36:05.015535+00:00 [queued]>
[2022-02-19 21:36:09,037] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data manual__2022-02-19T21:36:05.015535+00:00 [queued]>
[2022-02-19 21:36:09,039] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 21:36:09,039] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 21:36:09,041] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 21:36:09,090] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): pre.pre_get_data> on 2022-02-19 21:36:05.015535+00:00
[2022-02-19 21:36:09,102] {standard_task_runner.py:52} INFO - Started process 4613 to run task
[2022-02-19 21:36:09,108] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'pre.pre_get_data', 'manual__2022-02-19T21:36:05.015535+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpm3flh40c', '--error-file', '/tmp/tmp38hdb4kw']
[2022-02-19 21:36:09,110] {standard_task_runner.py:77} INFO - Job 8: Subtask pre.pre_get_data
[2022-02-19 21:36:09,280] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.pre.pre_get_data manual__2022-02-19T21:36:05.015535+00:00 [running]> on host ff48034dfdbf
[2022-02-19 21:36:09,448] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=pre.pre_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T21:36:05.015535+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T21:36:05.015535+00:00
[2022-02-19 21:37:09,388] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 21:37:09,404] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=pre.pre_get_data, execution_date=20220219T213605, start_date=20220219T213608, end_date=20220219T213709
[2022-02-19 21:37:09,469] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 21:37:09,519] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
