[2022-02-26 11:37:16,979] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-24T21:44:04.431894+00:00 [queued]>
[2022-02-26 11:37:16,999] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-24T21:44:04.431894+00:00 [queued]>
[2022-02-26 11:37:17,000] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-26 11:37:17,003] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-26 11:37:17,005] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-26 11:37:17,036] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): cat.cat_get_data> on 2022-02-24 21:44:04.431894+00:00
[2022-02-26 11:37:17,043] {standard_task_runner.py:52} INFO - Started process 135 to run task
[2022-02-26 11:37:17,051] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'cat.cat_get_data', 'scheduled__2022-02-24T21:44:04.431894+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpqcf40ae3', '--error-file', '/tmp/tmpziqs0hhr']
[2022-02-26 11:37:17,053] {standard_task_runner.py:77} INFO - Job 260: Subtask cat.cat_get_data
[2022-02-26 11:37:17,140] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.cat.cat_get_data scheduled__2022-02-24T21:44:04.431894+00:00 [running]> on host ff48034dfdbf
[2022-02-26 11:37:17,211] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=cat.cat_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-24T21:44:04.431894+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-24T21:44:04.431894+00:00
[2022-02-26 11:38:17,231] {python.py:175} INFO - Done. Returned value was: None
[2022-02-26 11:38:17,245] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=cat.cat_get_data, execution_date=20220224T214404, start_date=20220226T113716, end_date=20220226T113817
[2022-02-26 11:38:17,266] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-26 11:38:17,308] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
