[2022-02-23 21:39:57,031] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [queued]>
[2022-02-23 21:39:57,052] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [queued]>
[2022-02-23 21:39:57,053] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:39:57,054] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 21:39:57,055] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:39:57,072] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): pre.pre_get_data> on 2022-02-22 21:37:49.340300+00:00
[2022-02-23 21:39:57,079] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2022-02-23 21:39:57,086] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'pre.pre_get_data', 'scheduled__2022-02-22T21:37:49.340300+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpgx_9dzoo', '--error-file', '/tmp/tmpu0ubfo3m']
[2022-02-23 21:39:57,088] {standard_task_runner.py:77} INFO - Job 124: Subtask pre.pre_get_data
[2022-02-23 21:39:57,238] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:37:49.340300+00:00 [running]> on host ff48034dfdbf
[2022-02-23 21:39:57,361] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=pre.pre_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-22T21:37:49.340300+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-22T21:37:49.340300+00:00
[2022-02-23 21:40:57,375] {python.py:175} INFO - Done. Returned value was: None
[2022-02-23 21:40:57,393] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=pre.pre_get_data, execution_date=20220222T213749, start_date=20220223T213957, end_date=20220223T214057
[2022-02-23 21:40:57,434] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 21:40:57,495] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
