[2022-02-23 21:45:05,524] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:44:04.027723+00:00 [queued]>
[2022-02-23 21:45:05,549] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:44:04.027723+00:00 [queued]>
[2022-02-23 21:45:05,551] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:45:05,552] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 21:45:05,554] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:45:05,573] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): pre.pre_get_data> on 2022-02-22 21:44:04.027723+00:00
[2022-02-23 21:45:05,582] {standard_task_runner.py:52} INFO - Started process 524 to run task
[2022-02-23 21:45:05,588] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'tutorial', 'pre.pre_get_data', 'scheduled__2022-02-22T21:44:04.027723+00:00', '--job-id', '177', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpr9jyb065', '--error-file', '/tmp/tmp6bli30ru']
[2022-02-23 21:45:05,589] {standard_task_runner.py:77} INFO - Job 177: Subtask pre.pre_get_data
[2022-02-23 21:45:05,668] {logging_mixin.py:109} INFO - Running <TaskInstance: tutorial.pre.pre_get_data scheduled__2022-02-22T21:44:04.027723+00:00 [running]> on host ff48034dfdbf
[2022-02-23 21:45:05,734] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial
AIRFLOW_CTX_TASK_ID=pre.pre_get_data
AIRFLOW_CTX_EXECUTION_DATE=2022-02-22T21:44:04.027723+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-22T21:44:04.027723+00:00
[2022-02-23 21:46:05,726] {python.py:175} INFO - Done. Returned value was: None
[2022-02-23 21:46:05,744] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=tutorial, task_id=pre.pre_get_data, execution_date=20220222T214404, start_date=20220223T214505, end_date=20220223T214605
[2022-02-23 21:46:05,791] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 21:46:05,845] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
